apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-streamer-deployment
  labels:
    app: streamer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamer
  template:
    metadata:
      labels:
        app: streamer
    spec:
      containers:
      - name: event-streamer
        image: us-central1-docker.pkg.dev/jetrr-cloud/training-app/k8-event-streamer:latest
        volumeMounts:
        - name: secret-volume
          mountPath: "/etc/secret"
          readOnly: true
    volumes:
    - name: secret-volume
      secret:
        secretName: sa-keyfile