name: Build, Push and Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  DockerImagePushAndDeploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: jetrr-cloud
        export_default_credentials: true

    - name: Configure docker for GCP
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Setup project in GCP
      run: gcloud config set project jetrr-cloud

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: 'gpu-cluster-auto'
        location: 'us-central1-f'

    - name: Build Docker image
      run: docker build -t k8-event-streamer .

    - name: TAG Docker image for Production
      if: ${{ github.ref == 'refs/heads/main' }}
      run: docker tag k8-event-streamer us-central1-docker.pkg.dev/jetrr-cloud/training-app/k8-event-streamer

    - name: Push Docker image to Artifact Registry for Main
      if: ${{ github.ref == 'refs/heads/main' }}
      run: docker push us-central1-docker.pkg.dev/jetrr-cloud/training-app/k8-event-streamer

    - name: Deploy to GKE
      if: ${{ github.ref == 'refs/heads/main' }}
      run: kubectl apply -f deploy.yml